### ISSUE TITLE
Repo Missing License

### ISSUE THREAD

**Issue by joshua-software-dev** [jmacato/NSubsys#3]
I'd like to reuse some of the code in this repo in a open source project I'm making, but I couldn't find any license information in this repo or anywhere else such as nuget.

Its your code, and you may allow or disallow what you please, I just figured I'd make the effort to reach out before crossing any boundary.

If a permissive open source license is not what you'd like to do with this code, could I request specific permission to use it? I'm trying to make a CLI program to mimic the function to convert arbitrary exe's to the correct platform, but the byte level manipulation required goes over my head, and I wanted to request access for this purpose.

**Comment by jmacato** [comment]
Thank you for reaching out! This codebase is MIT Licensed so yeah, you're free to pull some code in here :) Even better if you give back haha!

**Comment by joshua-software-dev** [comment]
Awesome, thanks.
